/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Accordion: typeof import('src/components/ui/Accordion.astro')['Accordion']
  const Card: typeof import('src/components/ui/Card.astro')['Card']
  const H1: typeof import('src/components/ui/H1.astro')['H1']
  const H2: typeof import('src/components/ui/H2.astro')['H2']
  const H3: typeof import('src/components/ui/H3.astro')['H3']
  const H4: typeof import('src/components/ui/H4.astro')['H4']
  const Icon: typeof import('src/components/ui/Icon.astro')['Icon']
  const Image: typeof import('src/components/ui/Image.astro')['Image']
  const Scroller: typeof import('src/components/ui/Scroller.astro')['Scroller']
  const Section: typeof import('src/components/ui/Section.astro')['Section']
  const TheFooter: typeof import('src/components/TheFooter.astro')['TheFooter']
  const TheForm: typeof import('src/components/TheForm.astro')['TheForm']
  const TheHeader: typeof import('src/components/TheHeader.astro')['TheHeader']
  const TheModal: typeof import('src/components/TheModal.astro')['TheModal']
  const WpNav: typeof import('src/components/ui/WpNav.astro')['WpNav']
}
